### ISSUE TITLE
SystemUI crashes while releasing a wakelock

### ISSUE THREAD

**Issue by ponces** [phhusson/platform_frameworks_base#12]
SystemUI is crashing and restarting everytime the device receives a new notification and the user expands it to be able to read it from the lockscreen.

It seems caused by a wakelock not being correctly released...

This is the stack at the time the exception was thrown:

> --------- beginning of crash
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: FATAL EXCEPTION: main
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: Process: com.android.systemui, PID: 4691
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: java.lang.RuntimeException: WakeLock under-locked Doze
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at android.os.PowerManager$WakeLock.release(PowerManager.java:2461)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at android.os.PowerManager$WakeLock.release(PowerManager.java:2423)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at com.android.systemui.util.wakelock.WakeLock$1.release(WakeLock.java:112)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at com.android.systemui.util.wakelock.DelayedWakeLock.lambda$release$0(DelayedWakeLock.java:47)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at com.android.systemui.util.wakelock.DelayedWakeLock.lambda$release$0$DelayedWakeLock(Unknown Source:0)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at com.android.systemui.util.wakelock.-$$Lambda$DelayedWakeLock$aTG9u0wfrNahXJF_VixBxfvFqfg.run(Unknown Source:4)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> 01-18 17:47:54.445  4691  4691 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Attached is the full log - [wakelock.txt](https://github.com/phhusson/platform_frameworks_base/files/5832812/wakelock.txt)

**Comment by phhusson** [comment]
Someone else reported this crash on a Galaxy S20 FE
What's your device?

**Comment by ponces** [comment]
> Someone else reported this crash on a Galaxy S20 FE
> What's your device?

Samsung Galaxy A40

**Comment by ponces** [comment]
@phhusson 
Is this a solution? If so, could you please compile an image with this fix so I can test it?
Following some advices from [here](https://stackoverflow.com/questions/12140844/java-lang-runtimeexception-wakelock-under-locked-c2dm-lib), [here](https://github.com/evernote/android-job/issues/29) and [here](https://github.com/gotev/android-upload-service/issues/175)

![image](https://user-images.githubusercontent.com/4687488/106362732-5159b600-631c-11eb-93ed-f92e60d68f07.png)

**Comment by phhusson** [comment]
I don't think that this is the issue, the lock is "under-locked", so i'd guess it's held?

**Comment by ponces** [comment]
All those references that I mentioned are also "under-locked"... 🤔

**Comment by ponces** [comment]
Can confirm the fix is working using an updated SystemUI version!

**Comment by ponces** [comment]
@phhusson do you want me to create a PR for this or do you have a proper fix in mind?

**Comment by phhusson** [comment]
Nope go ahead with the pr

2 févr. 2021 01:44:51 Alberto Ponces <notifications@github.com>:

**Comment by ponces** [comment]
Done and closed! Thank you!

**Comment by ghost** [comment]
for me too on Zenfone Max Shot

**Comment by ponces** [comment]
> for me too on Zenfone Max Shot

For me it was fixed with v300.m which has the commit mentioned in this thread.
Which version are you running?
